"""atualizando horários

Revision ID: 1f66164747ca
Revises: ba5970bf3ac9
Create Date: 2024-11-02 18:28:30.674803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f66164747ca'
down_revision = 'ba5970bf3ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('paciente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('medico_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.alter_column('medico_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('paciente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('descricao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
