"""adicionando dia da semana

Revision ID: 436d449b2166
Revises: b19ac0996e5c
Create Date: 2024-11-06 21:03:48.162074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436d449b2166'
down_revision = 'b19ac0996e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dia_da_semana', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.drop_column('dia_da_semana')

    # ### end Alembic commands ###
