"""adicionando doutores

Revision ID: 9ae3110ee516
Revises: 0389801dfdef
Create Date: 2024-11-01 23:49:31.714241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae3110ee516'
down_revision = '0389801dfdef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('idade',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=3),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('idade',
               existing_type=sa.String(length=3),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
