"""Added paciente_id to Consulta

Revision ID: ba5970bf3ac9
Revises: 9ae3110ee516
Create Date: 2024-11-02 13:12:29.487677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5970bf3ac9'
down_revision = '9ae3110ee516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('paciente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('medico_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.alter_column('medico_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('paciente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('descricao',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
